name: Scala CI

on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        run: sbt test
        with:
          fail_ci_if_error: true